[general]
import = ["~/.dotfiles/alacritty/dark.toml"]

[colors]
cursor = { text = "CellBackground", cursor = "CellForeground" }

[env]
TERM = "alacritty"

[font]
builtin_box_drawing = true
size = 14.0

[font.normal]
family = "CodeNewRoman Nerd Font"

[font.offset]
x = 0
y = 3

[window]
option_as_alt = "BOTH"
# decorations = "Buttonless"
dynamic_padding = true

#
# xxd -psd
#
[[keyboard.bindings]]
chars = "\u00021"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00022"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00023"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00024"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00025"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00026"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00027"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00028"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00029"
key = "Key9"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002-"
key = "D"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002\\"
key = "D"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002z"
key = "Return"
mods = "Command"

#
# Better movements
#
[[keyboard.bindings]]
chars = "\u0002l"
key = "L"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002h"
key = "H"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002j"
key = "J"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002k"
key = "K"
mods = "Command"

#
# Resize panes
#
[[keyboard.bindings]]
chars = "\u0002\u0008"
key = "H"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002\u000a"
key = "J"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002\u000b"
key = "K"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002\u000c"
key = "L"
mods = "Command|Shift"

#
# Create new pane
#
[[keyboard.bindings]]
chars = "\u0002c"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002;"
key = "Semicolon"
mods = "Command"

[[keyboard.bindings]]
Action = "None"
key = "W"
mods = "Command"

[[keyboard.bindings]]
Action = "None"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002P"
key = "P"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002g"
key = "G"
mods = "Command"
